version: '3'
services:

  server:
    image: gitea/gitea:1
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3000:3000"
      - "2222:22"
    environment:
      USER_UID: 1000
      USER_GID: 1000
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
      restart_policy:
        condition: none
        #restart is managed by systemd
