version: '3'
services:

  <NAME>:
    build: <BUILD-PATH>
    image: <IMAGE-PATH>
    volumes:
      - <HOST-PATH>:<CONTAINER-PATH>
    ports:
      - <HOST-PORT>:<CONTAINER-PORT>
    environment:
      EXAMPLE_A: "TRUE"
      EXAMPLE_B: 0.1
      EXAMPLE_C: String
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "64M"
      restart_policy:
        condition: none
        #restart is managed by systemd
