version: '3'
services:
  <NAME>:
    build: <BUILD-PATH>
    image: <IMAGE-PATH>
    volumes:
      - <HOST-PATH>:<CONTAINER-PATH>
    ports:
      - "<HOST-PORT>:<CONTAINER-PORT>"
    environment:
      EXAMPLE_A: "TRUE"
      EXAMPLE_B: 0.1
      EXAMPLE_C: String
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "100M"
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s
        delay: 1s
