version: '3'
services:
  honeypot:
    build: .
    ports:
      - "2022:2022"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "100M"
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s
        delay: 1s
