version: '3'
services:

  honeypot:
    build: .
    ports:
      - "2022:2022"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "64M"
      restart_policy:
        condition: none
        #restart is managed by systemd
