version: '3'
services:
  worker:
    build: .
    ports:
      - "8081:80"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "64M"
      restart_policy:
        condition: on-failure
        max_attempts: 10
